### ISSUE TITLE
Missing bg image

### ISSUE THREAD

**Issue by ghosh** [mailtokamalnayan/soochi#2]
Seems like the default background image for the items are missing. Throws an error in the console. Also is making an extra request.

```js
GET http://soochi.com/images/bg.png 404 (Not Found)
```

**Comment by mailtokamalnayan** [comment]
Fixed.

![loader](https://cloud.githubusercontent.com/assets/2495633/20584590/2273f92a-b21a-11e6-9eb1-5d7948973bbe.gif)
